// Generated by view binder compiler. Do not edit!
package com.s22010198.eco.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.s22010198.eco.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHomeBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageButton btnHow;

  @NonNull
  public final ImageButton btnLogOut;

  @NonNull
  public final ImageButton btnSortWaste;

  @NonNull
  public final ImageView homeProfileImageView;

  @NonNull
  public final ImageView imageAboutus;

  @NonNull
  public final ImageView imageView4;

  @NonNull
  public final ImageView imgProfileSettings;

  @NonNull
  public final ImageButton recycleBtn;

  @NonNull
  public final TextView txtAboutus;

  @NonNull
  public final TextView txtMail;

  @NonNull
  public final TextView txtMap;

  @NonNull
  public final TextView txtProfileSettings;

  @NonNull
  public final TextView txtRec;

  @NonNull
  public final TextView txtSortWaste;

  @NonNull
  public final TextView txtlogout;

  private ActivityHomeBinding(@NonNull ConstraintLayout rootView, @NonNull ImageButton btnHow,
      @NonNull ImageButton btnLogOut, @NonNull ImageButton btnSortWaste,
      @NonNull ImageView homeProfileImageView, @NonNull ImageView imageAboutus,
      @NonNull ImageView imageView4, @NonNull ImageView imgProfileSettings,
      @NonNull ImageButton recycleBtn, @NonNull TextView txtAboutus, @NonNull TextView txtMail,
      @NonNull TextView txtMap, @NonNull TextView txtProfileSettings, @NonNull TextView txtRec,
      @NonNull TextView txtSortWaste, @NonNull TextView txtlogout) {
    this.rootView = rootView;
    this.btnHow = btnHow;
    this.btnLogOut = btnLogOut;
    this.btnSortWaste = btnSortWaste;
    this.homeProfileImageView = homeProfileImageView;
    this.imageAboutus = imageAboutus;
    this.imageView4 = imageView4;
    this.imgProfileSettings = imgProfileSettings;
    this.recycleBtn = recycleBtn;
    this.txtAboutus = txtAboutus;
    this.txtMail = txtMail;
    this.txtMap = txtMap;
    this.txtProfileSettings = txtProfileSettings;
    this.txtRec = txtRec;
    this.txtSortWaste = txtSortWaste;
    this.txtlogout = txtlogout;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnHow;
      ImageButton btnHow = ViewBindings.findChildViewById(rootView, id);
      if (btnHow == null) {
        break missingId;
      }

      id = R.id.btnLogOut;
      ImageButton btnLogOut = ViewBindings.findChildViewById(rootView, id);
      if (btnLogOut == null) {
        break missingId;
      }

      id = R.id.btnSortWaste;
      ImageButton btnSortWaste = ViewBindings.findChildViewById(rootView, id);
      if (btnSortWaste == null) {
        break missingId;
      }

      id = R.id.homeProfileImageView;
      ImageView homeProfileImageView = ViewBindings.findChildViewById(rootView, id);
      if (homeProfileImageView == null) {
        break missingId;
      }

      id = R.id.imageAboutus;
      ImageView imageAboutus = ViewBindings.findChildViewById(rootView, id);
      if (imageAboutus == null) {
        break missingId;
      }

      id = R.id.imageView4;
      ImageView imageView4 = ViewBindings.findChildViewById(rootView, id);
      if (imageView4 == null) {
        break missingId;
      }

      id = R.id.imgProfileSettings;
      ImageView imgProfileSettings = ViewBindings.findChildViewById(rootView, id);
      if (imgProfileSettings == null) {
        break missingId;
      }

      id = R.id.recycleBtn;
      ImageButton recycleBtn = ViewBindings.findChildViewById(rootView, id);
      if (recycleBtn == null) {
        break missingId;
      }

      id = R.id.txtAboutus;
      TextView txtAboutus = ViewBindings.findChildViewById(rootView, id);
      if (txtAboutus == null) {
        break missingId;
      }

      id = R.id.txtMail;
      TextView txtMail = ViewBindings.findChildViewById(rootView, id);
      if (txtMail == null) {
        break missingId;
      }

      id = R.id.txtMap;
      TextView txtMap = ViewBindings.findChildViewById(rootView, id);
      if (txtMap == null) {
        break missingId;
      }

      id = R.id.txtProfileSettings;
      TextView txtProfileSettings = ViewBindings.findChildViewById(rootView, id);
      if (txtProfileSettings == null) {
        break missingId;
      }

      id = R.id.txtRec;
      TextView txtRec = ViewBindings.findChildViewById(rootView, id);
      if (txtRec == null) {
        break missingId;
      }

      id = R.id.txtSortWaste;
      TextView txtSortWaste = ViewBindings.findChildViewById(rootView, id);
      if (txtSortWaste == null) {
        break missingId;
      }

      id = R.id.txtlogout;
      TextView txtlogout = ViewBindings.findChildViewById(rootView, id);
      if (txtlogout == null) {
        break missingId;
      }

      return new ActivityHomeBinding((ConstraintLayout) rootView, btnHow, btnLogOut, btnSortWaste,
          homeProfileImageView, imageAboutus, imageView4, imgProfileSettings, recycleBtn,
          txtAboutus, txtMail, txtMap, txtProfileSettings, txtRec, txtSortWaste, txtlogout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
