// Generated by view binder compiler. Do not edit!
package com.s22010198.eco.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ProgressBar;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.s22010198.eco.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityProfileBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button changeProfileImageBtn;

  @NonNull
  public final EditText editEmail;

  @NonNull
  public final EditText editName;

  @NonNull
  public final EditText editPassword;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final ImageView profileImageView;

  @NonNull
  public final ProgressBar progressBar3;

  @NonNull
  public final Button saveProfileBtn;

  private ActivityProfileBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button changeProfileImageBtn, @NonNull EditText editEmail,
      @NonNull EditText editName, @NonNull EditText editPassword, @NonNull ImageView imageView2,
      @NonNull ImageView profileImageView, @NonNull ProgressBar progressBar3,
      @NonNull Button saveProfileBtn) {
    this.rootView = rootView;
    this.changeProfileImageBtn = changeProfileImageBtn;
    this.editEmail = editEmail;
    this.editName = editName;
    this.editPassword = editPassword;
    this.imageView2 = imageView2;
    this.profileImageView = profileImageView;
    this.progressBar3 = progressBar3;
    this.saveProfileBtn = saveProfileBtn;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityProfileBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityProfileBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_profile, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityProfileBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.changeProfileImageBtn;
      Button changeProfileImageBtn = ViewBindings.findChildViewById(rootView, id);
      if (changeProfileImageBtn == null) {
        break missingId;
      }

      id = R.id.editEmail;
      EditText editEmail = ViewBindings.findChildViewById(rootView, id);
      if (editEmail == null) {
        break missingId;
      }

      id = R.id.editName;
      EditText editName = ViewBindings.findChildViewById(rootView, id);
      if (editName == null) {
        break missingId;
      }

      id = R.id.editPassword;
      EditText editPassword = ViewBindings.findChildViewById(rootView, id);
      if (editPassword == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.profileImageView;
      ImageView profileImageView = ViewBindings.findChildViewById(rootView, id);
      if (profileImageView == null) {
        break missingId;
      }

      id = R.id.progressBar3;
      ProgressBar progressBar3 = ViewBindings.findChildViewById(rootView, id);
      if (progressBar3 == null) {
        break missingId;
      }

      id = R.id.saveProfileBtn;
      Button saveProfileBtn = ViewBindings.findChildViewById(rootView, id);
      if (saveProfileBtn == null) {
        break missingId;
      }

      return new ActivityProfileBinding((ConstraintLayout) rootView, changeProfileImageBtn,
          editEmail, editName, editPassword, imageView2, profileImageView, progressBar3,
          saveProfileBtn);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
