// Generated by view binder compiler. Do not edit!
package com.s22010198.eco.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.s22010198.eco.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAboutUsBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView imageViewFacebook;

  @NonNull
  public final ImageView imageViewGoogle;

  @NonNull
  public final ImageView imageViewWhatsApp;

  @NonNull
  public final ImageButton imgBtnBack;

  @NonNull
  public final TextView textViewEmail;

  @NonNull
  public final TextView textViewName;

  @NonNull
  public final TextView textViewRegistrationNumber;

  @NonNull
  public final TextView textViewStudentNumber;

  @NonNull
  public final TextView textViewTitle;

  private ActivityAboutUsBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView imageViewFacebook, @NonNull ImageView imageViewGoogle,
      @NonNull ImageView imageViewWhatsApp, @NonNull ImageButton imgBtnBack,
      @NonNull TextView textViewEmail, @NonNull TextView textViewName,
      @NonNull TextView textViewRegistrationNumber, @NonNull TextView textViewStudentNumber,
      @NonNull TextView textViewTitle) {
    this.rootView = rootView;
    this.imageViewFacebook = imageViewFacebook;
    this.imageViewGoogle = imageViewGoogle;
    this.imageViewWhatsApp = imageViewWhatsApp;
    this.imgBtnBack = imgBtnBack;
    this.textViewEmail = textViewEmail;
    this.textViewName = textViewName;
    this.textViewRegistrationNumber = textViewRegistrationNumber;
    this.textViewStudentNumber = textViewStudentNumber;
    this.textViewTitle = textViewTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAboutUsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAboutUsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_about_us, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAboutUsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageViewFacebook;
      ImageView imageViewFacebook = ViewBindings.findChildViewById(rootView, id);
      if (imageViewFacebook == null) {
        break missingId;
      }

      id = R.id.imageViewGoogle;
      ImageView imageViewGoogle = ViewBindings.findChildViewById(rootView, id);
      if (imageViewGoogle == null) {
        break missingId;
      }

      id = R.id.imageViewWhatsApp;
      ImageView imageViewWhatsApp = ViewBindings.findChildViewById(rootView, id);
      if (imageViewWhatsApp == null) {
        break missingId;
      }

      id = R.id.imgBtnBack;
      ImageButton imgBtnBack = ViewBindings.findChildViewById(rootView, id);
      if (imgBtnBack == null) {
        break missingId;
      }

      id = R.id.textViewEmail;
      TextView textViewEmail = ViewBindings.findChildViewById(rootView, id);
      if (textViewEmail == null) {
        break missingId;
      }

      id = R.id.textViewName;
      TextView textViewName = ViewBindings.findChildViewById(rootView, id);
      if (textViewName == null) {
        break missingId;
      }

      id = R.id.textViewRegistrationNumber;
      TextView textViewRegistrationNumber = ViewBindings.findChildViewById(rootView, id);
      if (textViewRegistrationNumber == null) {
        break missingId;
      }

      id = R.id.textViewStudentNumber;
      TextView textViewStudentNumber = ViewBindings.findChildViewById(rootView, id);
      if (textViewStudentNumber == null) {
        break missingId;
      }

      id = R.id.textViewTitle;
      TextView textViewTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewTitle == null) {
        break missingId;
      }

      return new ActivityAboutUsBinding((ConstraintLayout) rootView, imageViewFacebook,
          imageViewGoogle, imageViewWhatsApp, imgBtnBack, textViewEmail, textViewName,
          textViewRegistrationNumber, textViewStudentNumber, textViewTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
