// Generated by view binder compiler. Do not edit!
package com.s22010198.eco.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.s22010198.eco.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegisterBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView imageView3;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final Button regBtn;

  @NonNull
  public final EditText regMail;

  @NonNull
  public final EditText regName;

  @NonNull
  public final EditText regPassword;

  @NonNull
  public final EditText regPassword2;

  @NonNull
  public final TextView registerTextView;

  @NonNull
  public final TextView textViewECO;

  @NonNull
  public final TextView txtLogin;

  private ActivityRegisterBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView imageView3,
      @NonNull ProgressBar progressBar, @NonNull Button regBtn, @NonNull EditText regMail,
      @NonNull EditText regName, @NonNull EditText regPassword, @NonNull EditText regPassword2,
      @NonNull TextView registerTextView, @NonNull TextView textViewECO,
      @NonNull TextView txtLogin) {
    this.rootView = rootView;
    this.imageView3 = imageView3;
    this.progressBar = progressBar;
    this.regBtn = regBtn;
    this.regMail = regMail;
    this.regName = regName;
    this.regPassword = regPassword;
    this.regPassword2 = regPassword2;
    this.registerTextView = registerTextView;
    this.textViewECO = textViewECO;
    this.txtLogin = txtLogin;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageView3;
      ImageView imageView3 = ViewBindings.findChildViewById(rootView, id);
      if (imageView3 == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.regBtn;
      Button regBtn = ViewBindings.findChildViewById(rootView, id);
      if (regBtn == null) {
        break missingId;
      }

      id = R.id.regMail;
      EditText regMail = ViewBindings.findChildViewById(rootView, id);
      if (regMail == null) {
        break missingId;
      }

      id = R.id.regName;
      EditText regName = ViewBindings.findChildViewById(rootView, id);
      if (regName == null) {
        break missingId;
      }

      id = R.id.regPassword;
      EditText regPassword = ViewBindings.findChildViewById(rootView, id);
      if (regPassword == null) {
        break missingId;
      }

      id = R.id.regPassword2;
      EditText regPassword2 = ViewBindings.findChildViewById(rootView, id);
      if (regPassword2 == null) {
        break missingId;
      }

      id = R.id.registerTextView;
      TextView registerTextView = ViewBindings.findChildViewById(rootView, id);
      if (registerTextView == null) {
        break missingId;
      }

      id = R.id.textViewECO;
      TextView textViewECO = ViewBindings.findChildViewById(rootView, id);
      if (textViewECO == null) {
        break missingId;
      }

      id = R.id.txtLogin;
      TextView txtLogin = ViewBindings.findChildViewById(rootView, id);
      if (txtLogin == null) {
        break missingId;
      }

      return new ActivityRegisterBinding((ConstraintLayout) rootView, imageView3, progressBar,
          regBtn, regMail, regName, regPassword, regPassword2, registerTextView, textViewECO,
          txtLogin);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
