// Generated by view binder compiler. Do not edit!
package com.s22010198.eco.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.s22010198.eco.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRecycleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageButton btnTips;

  @NonNull
  public final ImageView imageView6;

  @NonNull
  public final ImageButton imgBtnHome;

  @NonNull
  public final ImageButton recycleBtn;

  @NonNull
  public final TextView txtHow;

  @NonNull
  public final TextView txtTips;

  private ActivityRecycleBinding(@NonNull ConstraintLayout rootView, @NonNull ImageButton btnTips,
      @NonNull ImageView imageView6, @NonNull ImageButton imgBtnHome,
      @NonNull ImageButton recycleBtn, @NonNull TextView txtHow, @NonNull TextView txtTips) {
    this.rootView = rootView;
    this.btnTips = btnTips;
    this.imageView6 = imageView6;
    this.imgBtnHome = imgBtnHome;
    this.recycleBtn = recycleBtn;
    this.txtHow = txtHow;
    this.txtTips = txtTips;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRecycleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRecycleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_recycle, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRecycleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnTips;
      ImageButton btnTips = ViewBindings.findChildViewById(rootView, id);
      if (btnTips == null) {
        break missingId;
      }

      id = R.id.imageView6;
      ImageView imageView6 = ViewBindings.findChildViewById(rootView, id);
      if (imageView6 == null) {
        break missingId;
      }

      id = R.id.imgBtnHome;
      ImageButton imgBtnHome = ViewBindings.findChildViewById(rootView, id);
      if (imgBtnHome == null) {
        break missingId;
      }

      id = R.id.recycleBtn;
      ImageButton recycleBtn = ViewBindings.findChildViewById(rootView, id);
      if (recycleBtn == null) {
        break missingId;
      }

      id = R.id.txtHow;
      TextView txtHow = ViewBindings.findChildViewById(rootView, id);
      if (txtHow == null) {
        break missingId;
      }

      id = R.id.txtTips;
      TextView txtTips = ViewBindings.findChildViewById(rootView, id);
      if (txtTips == null) {
        break missingId;
      }

      return new ActivityRecycleBinding((ConstraintLayout) rootView, btnTips, imageView6,
          imgBtnHome, recycleBtn, txtHow, txtTips);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
